## Data Preprocessing

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/

Mounted at /gdrive
/gdrive

In [ ]:
%cd/gdrive/Shareddrives/Capstone Project/Data/TempPrecip

/gdrive/Shareddrives/Capstone Project/Data/TempPrecip

In [ ]:
import json
import pandas as pd
import numpy as np
import io
from dateutil.parser import parse 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

## Precip Data (avg precip value in NY counties)

In [ ]:
path = "/gdrive/Shareddrives/Capstone Project/Data/TempPrecip/NY_Precip_2002-01-01_2020-12-31"
filename = 'NY_Precip_2002-01-01_2020-12-31'
with open(path, 'r' ) as f:
  precip = json.load(f)

In [ ]:
res = [dict(zip(precip, i)) for i in zip(*precip.values())]
len(res)
type(res)
#[i.split('09001', 1)[0] for i in res]
dic = res.pop(0)
#type(dic)
l = dic['data']
#type(l)
l[0] #index of the dataframe

'2002-01-01'

In [ ]:
# for loop getting the date as index
# list of days
datelist = []
for d in res:
  #print(d)
  l = d['data']
  #print(type(l))
  datelist.append(l[0])

datelist
#type(datelist)

In [ ]:
# dict of county key and precip value
preciplist = []
for d in res:
  q = d['data']
  n = q[-1]
  preciplist.append(n)

In [ ]:
precip = pd.DataFrame(preciplist,index=datelist)
precip

               34003     33019     36049  ...     36073     42065     36079
2002-01-02  0.000000  0.000000  0.000000  ...  0.001288  0.003935  0.000000
2002-01-03  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2002-01-04  0.000000  0.000000  0.020870  ...  0.000000  0.003035  0.000000
2002-01-05  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2002-01-06  0.000000  0.000000  0.064998  ...  0.000000  0.000000  0.000000
...              ...       ...       ...  ...       ...       ...       ...
2020-12-27  0.000000  0.000000  0.326860  ...  0.086111  0.002376  0.000000
2020-12-28  0.000000  0.000000  0.033482  ...  0.045115  0.063547  0.000000
2020-12-29  0.001289  0.000000  0.275643  ...  0.015439  0.004665  0.000000
2020-12-30  0.000000  0.000000  0.000745  ...  0.000000  0.010501  0.000000
2020-12-31  0.184558  0.005496  0.394104  ...  0.375673  0.384720  0.207208

[6939 rows x 127 columns]

In [ ]:
# Precip DataFrame in NY Counties 
precip= precip[['36001', 
'36003', 
'36005',
'36007',
'36009',
'36011',
'36013',
'36015',
'36017',
'36019',
'36021',
'36023',
'36025',
'36027',
'36029',
'36031',
'36033',
'36035',
'36037',
'36039',
'36041',
'36043',
'36045',
'36047',
'36049',
'36051',
'36053',
'36055',
'36057',
'36059',
'36061',
'36063',
'36065',
'36067',
'36069',
'36071',
'36073',
'36075',
'36077',
'36079',
'36081',
'36083',
'36085',
'36087',
'36089',
'36091',
'36093',
'36095',
'36097',
'36099',
'36101',
'36103',
'36105',
'36107',
'36109',
'36111',
'36113',
'36115',
'36117',
'36119','36121',
'36123']]

## Temp Data (avg, max, and min temp value in NY counties)

In [ ]:
# temp
path = "/gdrive/Shareddrives/Capstone Project/Data/TempPrecip/NY_Temp_2000-01-01_2020-12-31"
filename = 'NY_Temp_2000-01-01_2020-12-31'
with open(path, 'r' ) as f:
  temp = json.load(f)

In [ ]:
res = [dict(zip(temp, i)) for i in zip(*temp.values())]
len(res)
type(res)
#[i.split('09001', 1)[0] for i in res]
dic = res.pop(0)
#type(dic)
l = dic['data']
#type(l)
l[0] #index of the dataframe

'2000-01-01'

In [ ]:
# for loop getting the date as index
# list of days
datelist1 = []
for d in res:
  #print(d)
  l = d['data']
  #print(type(l))
  datelist1.append(l[0])

datelist1
#type(datelist)

In [ ]:
# list of avg temp
temp_avg_list = []
for d in res:
  q = d['data']
  n = q[1]
  temp_avg_list.append(n)
temp_avg_list

In [ ]:
# list of max temp
temp_max_list = []
for d in res:
  q = d['data']
  n = q[2]
  temp_max_list.append(n)
temp_max_list

In [ ]:
# list of min temp
temp_min_list = []
for d in res:
  q = d['data']
  n = q[2]
  temp_min_list.append(n)
temp_min_list

In [ ]:
#datafram_AVG
#date as index, county id as column, input as avg temp
#average of daily avg_temp for that week
df_avg = pd.DataFrame(temp_avg_list,index=datelist1)
#df_avg

df_avg.index = pd.to_datetime(df_avg.index,format='%Y-%m-%d')
df_avg

df_avg = df_avg[['36001', 
'36003', 
'36005',
'36007',
'36009',
'36011',
'36013',
'36015',
'36017',
'36019',
'36021',
'36023',
'36025',
'36027',
'36029',
'36031',
'36033',
'36035',
'36037',
'36039',
'36041',
'36043',
'36045',
'36047',
'36049',
'36051',
'36053',
'36055',
'36057',
'36059',
'36061',
'36063',
'36065',
'36067',
'36069',
'36071',
'36073',
'36075',
'36077',
'36079',
'36081',
'36083',
'36085',
'36087',
'36089',
'36091',
'36093',
'36095',
'36097',
'36099',
'36101',
'36103',
'36105',
'36107',
'36109',
'36111',
'36113',
'36115',
'36117',
'36119','36121',
'36123']]

df2 = df_avg.copy()
df2.index = pd.to_datetime(df_avg.index,format='%Y-%m-%d')
df2['date'] = pd.to_datetime(df2.index)
avg_T_w= df2.resample('M',on='date').mean()
avg_T_w

                36001      36003      36005  ...      36119      36121      36123
date                                         ...
2000-01-31  16.296702  17.914986  28.928943  ...  25.336679  18.919986  19.279203
2000-02-29  22.391029  24.326885  34.412461  ...  31.825372  25.615585  26.666445
2000-03-31  36.947990  36.217542  44.626088  ...  42.950548  36.652953  37.751168
2000-04-30  42.019584  40.981156  48.457862  ...  47.565337  41.344286  41.925097
2000-05-31  55.979114  54.782148  60.868144  ...  59.477559  55.705702  57.110203
...               ...        ...        ...  ...        ...        ...        ...
2020-08-31  68.885569  66.819173  76.716053  ...  74.310295  67.918556  69.726182
2020-09-30  59.904833  57.609018  67.366080  ...  64.655673  59.725004  60.324417
2020-10-31  49.882962  47.469390  56.510659  ...  54.358538  48.454316  50.012897
2020-11-30  40.915615  40.891973  48.947233  ...  46.210760  43.656437  43.774173
2020-12-31  30.181538  28.369399  36.313724  ...  33.788851  29.514358  30.718531

[252 rows x 62 columns]

In [ ]:
avg_T_w.reset_index(inplace=True)

In [ ]:
avg_t = avg_T_w.melt(id_vars=['date'])
avg_t.columns = ['date','fips','avg_temp']

avg_t['fips'] = avg_t['fips'].astype(int)

avg_t

            date   fips   avg_temp
0     2000-01-31  36001  16.296702
1     2000-02-29  36001  22.391029
2     2000-03-31  36001  36.947990
3     2000-04-30  36001  42.019584
4     2000-05-31  36001  55.979114
...          ...    ...        ...
15619 2020-08-31  36123  69.726182
15620 2020-09-30  36123  60.324417
15621 2020-10-31  36123  50.012897
15622 2020-11-30  36123  43.774173
15623 2020-12-31  36123  30.718531

[15624 rows x 3 columns]

In [ ]:
#datafram_MAX
#date as index, county id as column, input as max temp
#average of daily max_temp for that week
df_max = pd.DataFrame(temp_max_list,index=datelist1)
df_max.index = pd.to_datetime(df_avg.index,format='%Y-%m-%d')
df_max = df_max[['36001', 
'36003', 
'36005',
'36007',
'36009',
'36011',
'36013',
'36015',
'36017',
'36019',
'36021',
'36023',
'36025',
'36027',
'36029',
'36031',
'36033',
'36035',
'36037',
'36039',
'36041',
'36043',
'36045',
'36047',
'36049',
'36051',
'36053',
'36055',
'36057',
'36059',
'36061',
'36063',
'36065',
'36067',
'36069',
'36071',
'36073',
'36075',
'36077',
'36079',
'36081',
'36083',
'36085',
'36087',
'36089',
'36091',
'36093',
'36095',
'36097',
'36099',
'36101',
'36103',
'36105',
'36107',
'36109',
'36111',
'36113',
'36115',
'36117',
'36119','36121',
'36123']]
df_max

df3 = df_max.copy()
df3.index = pd.to_datetime(df_max.index,format='%Y-%m-%d')
df3['date'] = pd.to_datetime(df3.index)
max_T_w= df3.resample('M',on='date').mean()
max_T_w

                36001      36003      36005  ...      36119      36121      36123
date                                         ...
2000-01-31  26.454686  28.726462  36.622854  ...  33.678223  27.958979  27.963608
2000-02-29  32.511959  35.124778  41.713134  ...  39.571143  34.170414  34.219237
2000-03-31  48.416708  48.175629  54.092776  ...  52.797825  46.080935  47.418871
2000-04-30  51.754220  51.500322  56.909875  ...  56.571987  49.601405  50.642671
2000-05-31  66.958694  68.167557  70.615824  ...  69.559152  65.366399  67.823182
...               ...        ...        ...  ...        ...        ...        ...
2020-08-31  79.673520  79.234119  86.676277  ...  85.002894  77.981692  80.926901
2020-09-30  71.487962  69.910907  77.212692  ...  75.615496  69.971207  71.771244
2020-10-31  59.773333  57.157991  64.832645  ...  63.368398  56.532017  58.397481
2020-11-30  51.564063  51.143302  58.879654  ...  57.381489  51.849078  52.859666
2020-12-31  38.436805  34.963770  43.684759  ...  42.129662  35.448089  36.490184

[252 rows x 62 columns]

In [ ]:
max_T_w.reset_index(inplace=True)

In [ ]:
max_t = max_T_w.melt(id_vars=['date'])
max_t.columns = ['date','fips','max_temp']

max_t['fips'] = max_t['fips'].astype(int)

max_t

            date   fips   max_temp
0     2000-01-31  36001  26.454686
1     2000-02-29  36001  32.511959
2     2000-03-31  36001  48.416708
3     2000-04-30  36001  51.754220
4     2000-05-31  36001  66.958694
...          ...    ...        ...
15619 2020-08-31  36123  80.926901
15620 2020-09-30  36123  71.771244
15621 2020-10-31  36123  58.397481
15622 2020-11-30  36123  52.859666
15623 2020-12-31  36123  36.490184

[15624 rows x 3 columns]

In [ ]:
#datafram_MIn
#date as index, county id as column, input as min temp
#average of daily min_temp for that week
df_min = pd.DataFrame(temp_min_list,index=datelist1)
df_min.index = pd.to_datetime(df_avg.index,format='%Y-%m-%d')

df_min = df_min[['36001', 
'36003', 
'36005',
'36007',
'36009',
'36011',
'36013',
'36015',
'36017',
'36019',
'36021',
'36023',
'36025',
'36027',
'36029',
'36031',
'36033',
'36035',
'36037',
'36039',
'36041',
'36043',
'36045',
'36047',
'36049',
'36051',
'36053',
'36055',
'36057',
'36059',
'36061',
'36063',
'36065',
'36067',
'36069',
'36071',
'36073',
'36075',
'36077',
'36079',
'36081',
'36083',
'36085',
'36087',
'36089',
'36091',
'36093',
'36095',
'36097',
'36099',
'36101',
'36103',
'36105',
'36107',
'36109',
'36111',
'36113',
'36115',
'36117',
'36119','36121',
'36123']]


df4 = df_min.copy()
df4.index = pd.to_datetime(df_min.index,format='%Y-%m-%d')
df4['date'] = pd.to_datetime(df4.index)
min_T_w= df4.resample('M',on='date').mean()
min_T_w

                36001      36003      36005  ...      36119      36121      36123
date                                         ...
2000-01-31  26.454686  28.726462  36.622854  ...  33.678223  27.958979  27.963608
2000-02-29  32.511959  35.124778  41.713134  ...  39.571143  34.170414  34.219237
2000-03-31  48.416708  48.175629  54.092776  ...  52.797825  46.080935  47.418871
2000-04-30  51.754220  51.500322  56.909875  ...  56.571987  49.601405  50.642671
2000-05-31  66.958694  68.167557  70.615824  ...  69.559152  65.366399  67.823182
...               ...        ...        ...  ...        ...        ...        ...
2020-08-31  79.673520  79.234119  86.676277  ...  85.002894  77.981692  80.926901
2020-09-30  71.487962  69.910907  77.212692  ...  75.615496  69.971207  71.771244
2020-10-31  59.773333  57.157991  64.832645  ...  63.368398  56.532017  58.397481
2020-11-30  51.564063  51.143302  58.879654  ...  57.381489  51.849078  52.859666
2020-12-31  38.436805  34.963770  43.684759  ...  42.129662  35.448089  36.490184

[252 rows x 62 columns]

In [ ]:
min_T_w.reset_index(inplace=True)

In [ ]:
min_t = min_T_w.melt(id_vars=['date'])
min_t.columns = ['date','fips','min_temp']

min_t['fips'] = min_t['fips'].astype(int)

min_t

            date   fips   min_temp
0     2000-01-31  36001  26.454686
1     2000-02-29  36001  32.511959
2     2000-03-31  36001  48.416708
3     2000-04-30  36001  51.754220
4     2000-05-31  36001  66.958694
...          ...    ...        ...
15619 2020-08-31  36123  80.926901
15620 2020-09-30  36123  71.771244
15621 2020-10-31  36123  58.397481
15622 2020-11-30  36123  52.859666
15623 2020-12-31  36123  36.490184

[15624 rows x 3 columns]

## Merge 3 Weekly Temp dataframes into 1 (df)

In [ ]:
# merge Temp Avg, Min, Max
avg_t['max_temp'] = max_t['max_temp']
avg_t['min_temp'] = min_t['min_temp']

In [ ]:
name = pd.read_csv('fips_county.csv')
name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fips    62 non-null     int64
 1   county  62 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.1+ KB

In [ ]:
temp_w = avg_t.merge(name, left_on='fips', right_on='fips')
temp_w

            date   fips   avg_temp   max_temp   min_temp  county
0     2000-01-31  36001  16.296702  26.454686  26.454686  Albany
1     2000-02-29  36001  22.391029  32.511959  32.511959  Albany
2     2000-03-31  36001  36.947990  48.416708  48.416708  Albany
3     2000-04-30  36001  42.019584  51.754220  51.754220  Albany
4     2000-05-31  36001  55.979114  66.958694  66.958694  Albany
...          ...    ...        ...        ...        ...     ...
15619 2020-08-31  36123  69.726182  80.926901  80.926901   Yates
15620 2020-09-30  36123  60.324417  71.771244  71.771244   Yates
15621 2020-10-31  36123  50.012897  58.397481  58.397481   Yates
15622 2020-11-30  36123  43.774173  52.859666  52.859666   Yates
15623 2020-12-31  36123  30.718531  36.490184  36.490184   Yates

[15624 rows x 6 columns]

In [ ]:
temp_w.describe()

               fips      avg_temp      max_temp      min_temp
count  15624.000000  15624.000000  15624.000000  15624.000000
mean   36062.000000     46.856393     56.582537     56.582537
std       35.792206     17.385390     18.200665     18.200665
min    36001.000000      1.328605     12.117121     12.117121
25%    36031.000000     31.501401     39.723437     39.723437
50%    36062.000000     47.465736     57.354700     57.354700
75%    36093.000000     63.143498     73.709127     73.709127
max    36123.000000     80.169361     91.075557     91.075557

In [ ]:
temp_w['Month'] = temp_w['date'].dt.month
temp_m_gs = temp_w[(temp_w['Month'] >= 5) & (temp_w['Month'] <= 9)]
temp_m_gs.columns

            date   fips   avg_temp   max_temp   min_temp  county  Month
4     2000-05-31  36001  55.979114  66.958694  66.958694  Albany      5
5     2000-06-30  36001  62.998186  73.718376  73.718376  Albany      6
6     2000-07-31  36001  64.445511  74.800593  74.800593  Albany      7
7     2000-08-31  36001  64.949083  75.336694  75.336694  Albany      8
8     2000-09-30  36001  57.459756  68.759148  68.759148  Albany      9
...          ...    ...        ...        ...        ...     ...    ...
15616 2020-05-31  36123  54.527653  65.463893  65.463893   Yates      5
15617 2020-06-30  36123  66.060735  77.423859  77.423859   Yates      6
15618 2020-07-31  36123  73.508565  84.233874  84.233874   Yates      7
15619 2020-08-31  36123  69.726182  80.926901  80.926901   Yates      8
15620 2020-09-30  36123  60.324417  71.771244  71.771244   Yates      9

[6510 rows x 7 columns]

In [ ]:
temp_m_gs.to_csv('GS_Temp_M.csv',index=False)
from google.colab import files

files.download('GS_Temp_M.csv')

In [ ]:
temp_w.to_csv('GS_Temp_W.csv',index=False)
from google.colab import files

files.download('GS_Temp_W.csv')

## Precip Weekly Dataframe
> seperate Year and Month Columns

In [ ]:
df1 = precip.copy()
df1.index = pd.to_datetime(precip.index,format='%Y-%m-%d')
df1['date'] = pd.to_datetime(df1.index)
precip_w= df1.resample('M',on='date').mean()
precip_w

               36001     36003     36005  ...     36119     36121     36123
date                                      ...
2002-01-31  0.060860  0.052917  0.061112  ...  0.058375  0.068903  0.059267
2002-02-28  0.083086  0.076065  0.025401  ...  0.044142  0.105796  0.053187
2002-03-31  0.103687  0.079968  0.125913  ...  0.128268  0.094558  0.069872
2002-04-30  0.096234  0.111499  0.140060  ...  0.133607  0.138186  0.100917
2002-05-31  0.157132  0.173305  0.112541  ...  0.185056  0.194459  0.145985
...              ...       ...       ...  ...       ...       ...       ...
2020-08-31  0.216520  0.071950  0.161931  ...  0.123119  0.092961  0.103281
2020-09-30  0.103882  0.077787  0.135236  ...  0.132664  0.070080  0.062657
2020-10-31  0.102471  0.115422  0.180794  ...  0.154403  0.153949  0.095571
2020-11-30  0.075095  0.056716  0.097577  ...  0.105346  0.083300  0.036829
2020-12-31  0.201241  0.107409  0.155672  ...  0.186845  0.126073  0.102435

[228 rows x 62 columns]

In [ ]:
precip_w.reset_index(inplace=True)

In [ ]:
precip_w

          date     36001     36003  ...     36119     36121     36123
0   2002-01-31  0.060860  0.052917  ...  0.058375  0.068903  0.059267
1   2002-02-28  0.083086  0.076065  ...  0.044142  0.105796  0.053187
2   2002-03-31  0.103687  0.079968  ...  0.128268  0.094558  0.069872
3   2002-04-30  0.096234  0.111499  ...  0.133607  0.138186  0.100917
4   2002-05-31  0.157132  0.173305  ...  0.185056  0.194459  0.145985
..         ...       ...       ...  ...       ...       ...       ...
223 2020-08-31  0.216520  0.071950  ...  0.123119  0.092961  0.103281
224 2020-09-30  0.103882  0.077787  ...  0.132664  0.070080  0.062657
225 2020-10-31  0.102471  0.115422  ...  0.154403  0.153949  0.095571
226 2020-11-30  0.075095  0.056716  ...  0.105346  0.083300  0.036829
227 2020-12-31  0.201241  0.107409  ...  0.186845  0.126073  0.102435

[228 rows x 63 columns]

In [ ]:
pre_w = precip_w.melt(id_vars=['date'])
pre_w.columns=['date','fips','ave_precip']
pre_w['fips'] = pre_w['fips'].astype(int)
pre_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14136 entries, 0 to 14135
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        14136 non-null  datetime64[ns]
 1   fips        14136 non-null  int64
 2   ave_precip  14094 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 331.4 KB

In [ ]:
name = pd.read_csv('fips_county.csv')
name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fips    62 non-null     int64
 1   county  62 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.1+ KB

In [ ]:
pre_w = pre_w.merge(name, left_on='fips', right_on='fips')

In [ ]:
pre_w.county.nunique()

In [ ]:
pre_w['Month'] = pre_w['date'].dt.month
pre_m_gs = pre_w[(pre_w['Month'] >= 5) & (pre_w['Month'] <= 9)]
pre_m_gs

            date   fips  ave_precip  Month
4     2002-05-31  36001    0.157132      5
5     2002-06-30  36001    0.166913      6
6     2002-07-31  36001    0.055652      7
7     2002-08-31  36001    0.136340      8
8     2002-09-30  36001    0.102370      9
...          ...    ...         ...    ...
14128 2020-05-31  36123    0.109815      5
14129 2020-06-30  36123    0.058758      6
14130 2020-07-31  36123    0.134056      7
14131 2020-08-31  36123    0.103281      8
14132 2020-09-30  36123    0.062657      9

[5890 rows x 4 columns]

In [ ]:
pre_m_gs = pre_m_gs.merge(name, left_on='fips', right_on='fips')
pre_m_gs

           date   fips  ave_precip  Month  county
0    2002-05-31  36001    0.157132      5  Albany
1    2002-06-30  36001    0.166913      6  Albany
2    2002-07-31  36001    0.055652      7  Albany
3    2002-08-31  36001    0.136340      8  Albany
4    2002-09-30  36001    0.102370      9  Albany
...         ...    ...         ...    ...     ...
5885 2020-05-31  36123    0.109815      5   Yates
5886 2020-06-30  36123    0.058758      6   Yates
5887 2020-07-31  36123    0.134056      7   Yates
5888 2020-08-31  36123    0.103281      8   Yates
5889 2020-09-30  36123    0.062657      9   Yates

[5890 rows x 5 columns]

In [ ]:
pre_m_gs.to_csv('GS_Avg_Precip_M.csv',index=False)
from google.colab import files

files.download('GS_Avg_Precip_M.csv')

In [ ]:
pre_w.to_csv('GS_Avg_Precip_W.csv',index=False)
from google.colab import files

files.download('GS_Avg_Precip_W.csv')