In [38]:
import pandas as pd
import numpy as np
import json
import os
import datetime as dt
import seaborn as sns
import plotly.express as px
from urllib.request import urlopen
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import sklearn.metrics as metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

### Load the USDA data

In [4]:
path = '../../../../../../../Google Drive/Shared drives/Capstone Project/Data/USDA/'
filename = 'corn_cleaned'

In [5]:
usda_df = pd.read_csv(path+filename+'.csv')

In [6]:
usda_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21463 entries, 0 to 21462
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Program           21463 non-null  object
 1   Year              21463 non-null  int64
 2   Ag District       21463 non-null  object
 3   Ag District Code  21463 non-null  int64
 4   County            21463 non-null  object
 5   County ANSI       20838 non-null  float64
 6   Commodity         21463 non-null  object
 7   Data Item         21463 non-null  object
 8   Domain            21463 non-null  object
 9   Domain Category   21463 non-null  object
 10  Value             21463 non-null  float64
 11  CV (%)            1946 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 2.0+ MB

In [7]:
# Make USDA Data Item subsets
usda_df_yield = usda_df[usda_df["Data Item"]=="CORN GRAIN - YIELD MEASURED IN BU / ACRE"].copy()
usda_df_acrplanted = usda_df[usda_df["Data Item"]=="CORN - ACRES PLANTED"].copy()

In [8]:
print(usda_df_yield.shape)
print(usda_df_acrplanted.shape)

(2344, 12)
(2372, 12)

In [9]:
print(usda_df_yield.nunique())
print(usda_df_acrplanted.nunique())

Program               1
Year                 48
Ag District           9
Ag District Code      9
County               54
County ANSI          53
Commodity             1
Data Item             1
Domain                1
Domain Category       1
Value               472
CV (%)                0
dtype: int64
Program               1
Year                 48
Ag District           9
Ag District Code      9
County               55
County ANSI          54
Commodity             1
Data Item             1
Domain                1
Domain Category       1
Value               595
CV (%)                0
dtype: int64

In [12]:
print(usda_df_yield.County.unique())
print(usda_df_acrplanted.County.unique())

['CAYUGA' 'CORTLAND' 'HERKIMER' 'MADISON' 'ONEIDA' 'ONONDAGA'
 'OTHER (COMBINED) COUNTIES' 'OTSEGO' 'RENSSELAER' 'WASHINGTON' 'SUFFOLK'
 'JEFFERSON' 'LEWIS' 'ST LAWRENCE' 'COLUMBIA' 'DUTCHESS' 'ORANGE' 'ULSTER'
 'CHAUTAUQUA' 'STEUBEN' 'ERIE' 'GENESEE' 'LIVINGSTON' 'MONROE' 'ONTARIO'
 'SENECA' 'WAYNE' 'WYOMING' 'YATES' 'CHENANGO' 'MONTGOMERY' 'SARATOGA'
 'BROOME' 'CHEMUNG' 'SCHUYLER' 'TIOGA' 'TOMPKINS' 'ALLEGANY' 'CATTARAUGUS'
 'NIAGARA' 'OSWEGO' 'ALBANY' 'CLINTON' 'DELAWARE' 'SCHOHARIE' 'FULTON'
 'ORLEANS' 'SCHENECTADY' 'SULLIVAN' 'GREENE' 'FRANKLIN' 'ESSEX' 'WARREN'
 'PUTNAM']
['CAYUGA' 'CORTLAND' 'HERKIMER' 'MADISON' 'ONEIDA' 'ONONDAGA'
 'OTHER (COMBINED) COUNTIES' 'OTSEGO' 'RENSSELAER' 'WASHINGTON' 'SUFFOLK'
 'JEFFERSON' 'LEWIS' 'ST LAWRENCE' 'COLUMBIA' 'DUTCHESS' 'ORANGE' 'ULSTER'
 'CHAUTAUQUA' 'STEUBEN' 'ERIE' 'GENESEE' 'LIVINGSTON' 'MONROE' 'ONTARIO'
 'SENECA' 'WAYNE' 'WYOMING' 'YATES' 'CHENANGO' 'MONTGOMERY' 'SARATOGA'
 'BROOME' 'CHEMUNG' 'SCHUYLER' 'TIOGA' 'TOMPKINS' 'ALLEGANY' 'CATTARAUGUS'
 'NIAGARA' 'OSWEGO' 'ALBANY' 'CLINTON' 'DELAWARE' 'SCHOHARIE' 'FULTON'
 'ORLEANS' 'SCHENECTADY' 'SULLIVAN' 'GREENE' 'FRANKLIN' 'ESSEX' 'WARREN'
 'PUTNAM' 'WESTCHESTER']

In [17]:
usda_df_acrplanted[usda_df_acrplanted['County'] == 'WESTCHESTER']

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
20063,SURVEY,1976,SOUTHEAST,90,WESTCHESTER,119.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,200.0,NaN
20507,SURVEY,1975,SOUTHEAST,90,WESTCHESTER,119.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,200.0,NaN
20899,SURVEY,1974,SOUTHEAST,90,WESTCHESTER,119.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,200.0,NaN
21172,SURVEY,1973,SOUTHEAST,90,WESTCHESTER,119.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,300.0,NaN
21382,SURVEY,1972,SOUTHEAST,90,WESTCHESTER,119.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,500.0,NaN

### Loading USDA and USDM file

In [18]:
path = '../../../../../../../Google Drive/Shared drives/Capstone Project/Data/USDM/'
filename = 'USDM-USDA_112000-12312020'
usdm_usda = pd.read_csv(path+filename+'.csv')

In [19]:
print(usdm_usda.shape)
usdm_usda.head()

(803, 6)

   Year       County  ADSCI_yr  Yield  Acres_Planted  ADSCI_gs
0  2000       albany      0.00   86.0         3600.0       0.0
1  2000     allegany      0.00  103.0        10700.0       0.0
2  2000       broome      0.00   93.0         5400.0       0.0
3  2000  cattaraugus     48.66   97.0        18100.0       0.0
4  2000       cayuga      0.00   99.0        61900.0       0.0

In [20]:
usdm_usda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           803 non-null    int64
 1   County         803 non-null    object
 2   ADSCI_yr       803 non-null    float64
 3   Yield          803 non-null    float64
 4   Acres_Planted  803 non-null    float64
 5   ADSCI_gs       803 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 37.8+ KB

### Loading Temperature and Precipitation data

In [22]:
path = '../../../../../../../Google Drive/Shared drives/Capstone Project/Data/TempPrecip/'

In [23]:
filename = 'acrplanted_temp'
acrplanted_temp = pd.read_csv(path+filename+'.csv')

In [24]:
filename = 'yield_temp'
yield_temp = pd.read_csv(path+filename+'.csv')

In [25]:
filename = 'acrplanted_pre'
acrplanted_pre = pd.read_csv(path+filename+'.csv')

In [26]:
filename = 'yield_pre'
yield_pre = pd.read_csv(path+filename+'.csv')

In [27]:
print(acrplanted_temp.shape)
acrplanted_temp.head()

(821, 36)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,71.928196,82.672664,52.0,55.369206,18.709620,21.655916,41.021592,58.380542,71.928196,82.672664
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,69.330869,81.426583,52.0,53.584768,18.819448,20.092644,38.228930,56.810629,69.330869,81.426583
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,68.650213,80.420651,52.0,51.680985,19.338125,17.043280,35.545334,54.124641,68.650213,80.420651
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,71.419907,82.227218,52.0,54.487731,19.362260,20.218844,38.739829,57.642096,71.419907,82.227218
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,71.487308,82.502397,52.0,53.900447,19.620299,18.740218,37.736120,55.763216,71.487308,82.502397

In [28]:
print(yield_temp.shape)
yield_temp.head()

(821, 36)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,71.928196,82.672664,52.0,55.369206,18.709620,21.655916,41.021592,58.380542,71.928196,82.672664
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,69.330869,81.426583,52.0,53.584768,18.819448,20.092644,38.228930,56.810629,69.330869,81.426583
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,68.650213,80.420651,52.0,51.680985,19.338125,17.043280,35.545334,54.124641,68.650213,80.420651
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,71.419907,82.227218,52.0,54.487731,19.362260,20.218844,38.739829,57.642096,71.419907,82.227218
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,71.487308,82.502397,52.0,53.900447,19.620299,18.740218,37.736120,55.763216,71.487308,82.502397

In [29]:
print(acrplanted_pre.shape)
acrplanted_pre.head()

(719, 20)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,Value,CV (%),avg_precip_count,avg_precip_mean,avg_precip_std,avg_precip_min,avg_precip_25%,avg_precip_50%,avg_precip_75%,avg_precip_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,68000.0,NaN,52.0,0.126284,0.088166,0.011262,0.064633,0.108586,0.162758,0.364602
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,16000.0,NaN,52.0,0.136549,0.094494,0.008701,0.052037,0.116943,0.184175,0.391079
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,15400.0,NaN,52.0,0.163455,0.104624,0.003057,0.089469,0.134099,0.207785,0.490518
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,26600.0,NaN,52.0,0.137838,0.091820,0.008370,0.069401,0.110289,0.185823,0.375661
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,34700.0,NaN,52.0,0.166656,0.110897,0.005187,0.077669,0.146137,0.232315,0.479629

In [30]:
print(yield_pre.shape)
yield_pre.head()

(719, 20)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,Value,CV (%),avg_precip_count,avg_precip_mean,avg_precip_std,avg_precip_min,avg_precip_25%,avg_precip_50%,avg_precip_75%,avg_precip_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,158.0,NaN,52.0,0.126284,0.088166,0.011262,0.064633,0.108586,0.162758,0.364602
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,157.6,NaN,52.0,0.136549,0.094494,0.008701,0.052037,0.116943,0.184175,0.391079
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,147.9,NaN,52.0,0.163455,0.104624,0.003057,0.089469,0.134099,0.207785,0.490518
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,139.3,NaN,52.0,0.137838,0.091820,0.008370,0.069401,0.110289,0.185823,0.375661
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,154.4,NaN,52.0,0.166656,0.110897,0.005187,0.077669,0.146137,0.232315,0.479629

### Loading Temperature and Precipitation data - Growing Season

In [58]:
path = '../../../../../../../Google Drive/Shared drives/Capstone Project/Data/TempPrecip/'

In [59]:
filename = 'gs_acrplanted_temp'
gs_acrplanted_temp = pd.read_csv(path+filename+'.csv')

In [60]:
filename = 'gs_yield_temp'
gs_yield_temp = pd.read_csv(path+filename+'.csv')

In [61]:
filename = 'gs_acrplanted_pre'
gs_acrplanted_pre = pd.read_csv(path+filename+'.csv')

In [62]:
filename = 'gs_yield_pre'
gs_yield_pre = pd.read_csv(path+filename+'.csv')

In [63]:
print(gs_acrplanted_temp.shape)
gs_acrplanted_temp.head()

(821, 36)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,77.090020,80.920134,5.0,73.465390,6.475191,63.598835,72.181908,73.536051,77.090020,80.920134
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,75.424076,79.443288,5.0,71.839454,6.421871,62.222266,70.520350,71.587292,75.424076,79.443288
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,74.668479,78.492434,5.0,70.514132,6.802492,60.629280,67.985406,70.795059,74.668479,78.492434
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,76.765589,81.324519,5.0,73.232329,6.763674,63.127771,71.532990,73.410773,76.765589,81.324519
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,77.010881,80.978923,5.0,72.992763,6.971431,62.447200,71.213033,73.313780,77.010881,80.978923

In [64]:
print(gs_yield_temp.shape)
gs_yield_temp.head()

(821, 36)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,77.090020,80.920134,5.0,73.465390,6.475191,63.598835,72.181908,73.536051,77.090020,80.920134
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,75.424076,79.443288,5.0,71.839454,6.421871,62.222266,70.520350,71.587292,75.424076,79.443288
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,74.668479,78.492434,5.0,70.514132,6.802492,60.629280,67.985406,70.795059,74.668479,78.492434
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,76.765589,81.324519,5.0,73.232329,6.763674,63.127771,71.532990,73.410773,76.765589,81.324519
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,...,77.010881,80.978923,5.0,72.992763,6.971431,62.447200,71.213033,73.313780,77.010881,80.978923

In [65]:
print(gs_acrplanted_pre.shape)
gs_acrplanted_pre.head()

(719, 20)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,Value,CV (%),avg_precip_count,avg_precip_mean,avg_precip_std,avg_precip_min,avg_precip_25%,avg_precip_50%,avg_precip_75%,avg_precip_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,68000.0,NaN,5.0,0.149691,0.027505,0.103609,0.148900,0.155022,0.168161,0.172765
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,16000.0,NaN,5.0,0.133026,0.049193,0.066482,0.107747,0.129195,0.177460,0.184246
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,15400.0,NaN,5.0,0.166130,0.040688,0.116608,0.135810,0.165355,0.206235,0.206644
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,26600.0,NaN,5.0,0.142862,0.035050,0.087447,0.139894,0.141702,0.167130,0.178136
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,34700.0,NaN,5.0,0.175254,0.043610,0.120228,0.148319,0.185052,0.187310,0.235360

In [66]:
print(gs_yield_pre.shape)
gs_yield_pre.head()

(719, 20)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,Value,CV (%),avg_precip_count,avg_precip_mean,avg_precip_std,avg_precip_min,avg_precip_25%,avg_precip_50%,avg_precip_75%,avg_precip_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,158.0,NaN,5.0,0.149691,0.027505,0.103609,0.148900,0.155022,0.168161,0.172765
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,157.6,NaN,5.0,0.133026,0.049193,0.066482,0.107747,0.129195,0.177460,0.184246
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,147.9,NaN,5.0,0.166130,0.040688,0.116608,0.135810,0.165355,0.206235,0.206644
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,139.3,NaN,5.0,0.142862,0.035050,0.087447,0.139894,0.141702,0.167130,0.178136
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN GRAIN - YIELD MEASURED IN BU / ACRE,TOTAL,NOT SPECIFIED,154.4,NaN,5.0,0.175254,0.043610,0.120228,0.148319,0.185052,0.187310,0.235360

### Merging USDM-USDA and the Temp and Precip files

In [32]:
temp_precip = acrplanted_pre.merge(acrplanted_temp, how='inner', on=['Year','County'],
                         suffixes=('','_drop')).filter(regex='^(?!.*drop)')
print(temp_precip.shape)
temp_precip.head()

(719, 44)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,71.928196,82.672664,52.0,55.369206,18.709620,21.655916,41.021592,58.380542,71.928196,82.672664
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,69.330869,81.426583,52.0,53.584768,18.819448,20.092644,38.228930,56.810629,69.330869,81.426583
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,68.650213,80.420651,52.0,51.680985,19.338125,17.043280,35.545334,54.124641,68.650213,80.420651
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,71.419907,82.227218,52.0,54.487731,19.362260,20.218844,38.739829,57.642096,71.419907,82.227218
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,71.487308,82.502397,52.0,53.900447,19.620299,18.740218,37.736120,55.763216,71.487308,82.502397

In [33]:
temp_precip.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 719 entries, 0 to 718
Data columns (total 44 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Program           719 non-null    object
 1   Year              719 non-null    int64
 2   Ag District       719 non-null    object
 3   Ag District Code  719 non-null    int64
 4   County            719 non-null    object
 5   County ANSI       719 non-null    float64
 6   Commodity         719 non-null    object
 7   Data Item         719 non-null    object
 8   Domain            719 non-null    object
 9   Domain Category   719 non-null    object
 10  Value             719 non-null    float64
 11  CV (%)            0 non-null      float64
 12  avg_precip_count  719 non-null    float64
 13  avg_precip_mean   719 non-null    float64
 14  avg_precip_std    719 non-null    float64
 15  avg_precip_min    719 non-null    float64
 16  avg_precip_25%    719 non-null    float64
 17  avg_precip_50%    719 non-null    float64
 18  avg_precip_75%    719 non-null    float64
 19  avg_precip_max    719 non-null    float64
 20  avg_temp_count    719 non-null    float64
 21  avg_temp_mean     719 non-null    float64
 22  avg_temp_std      719 non-null    float64
 23  avg_temp_min      719 non-null    float64
 24  avg_temp_25%      719 non-null    float64
 25  avg_temp_50%      719 non-null    float64
 26  avg_temp_75%      719 non-null    float64
 27  avg_temp_max      719 non-null    float64
 28  max_temp_count    719 non-null    float64
 29  max_temp_mean     719 non-null    float64
 30  max_temp_std      719 non-null    float64
 31  max_temp_min      719 non-null    float64
 32  max_temp_25%      719 non-null    float64
 33  max_temp_50%      719 non-null    float64
 34  max_temp_75%      719 non-null    float64
 35  max_temp_max      719 non-null    float64
 36  min_temp_count    719 non-null    float64
 37  min_temp_mean     719 non-null    float64
 38  min_temp_std      719 non-null    float64
 39  min_temp_min      719 non-null    float64
 40  min_temp_25%      719 non-null    float64
 41  min_temp_50%      719 non-null    float64
 42  min_temp_75%      719 non-null    float64
 43  min_temp_max      719 non-null    float64
dtypes: float64(35), int64(2), object(7)
memory usage: 252.8+ KB

In [34]:
final_ml = usdm_usda.merge(temp_precip, how='inner', on=['Year','County'],
                         suffixes=('','_drop')).filter(regex='^(?!.*drop)')
print(final_ml.shape)
final_ml.head()

(703, 48)

,Year,County,ADSCI_yr,Yield,Acres_Planted,ADSCI_gs,Program,Ag District,Ag District Code,County ANSI,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,2002,albany,3918.70,83.0,4300.0,1207.14,SURVEY,EASTERN,60,1.0,...,74.135961,91.435192,52.0,57.267401,19.019907,29.170256,40.046174,53.811858,74.135961,91.435192
1,2002,allegany,898.71,100.0,12700.0,457.29,SURVEY,SOUTHWEST,70,3.0,...,74.758686,86.775847,52.0,55.975687,19.096036,26.277575,37.915611,53.284342,74.758686,86.775847
2,2002,broome,1897.18,110.0,7200.0,770.66,SURVEY,SOUTHERN,80,7.0,...,75.847577,91.179974,52.0,57.443196,18.952634,26.849015,41.009295,54.536745,75.847577,91.179974
3,2002,cattaraugus,468.99,117.0,19100.0,340.11,SURVEY,SOUTHWEST,70,9.0,...,74.324339,85.425502,52.0,55.684203,18.915017,25.702879,38.443219,53.241232,74.324339,85.425502
4,2002,cayuga,714.56,94.0,61200.0,570.89,SURVEY,CENTRAL,50,11.0,...,75.663489,91.396853,52.0,57.485600,18.870793,29.504130,41.022595,53.795674,75.663489,91.396853

In [35]:
final_ml.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 703 entries, 0 to 702
Data columns (total 48 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              703 non-null    int64
 1   County            703 non-null    object
 2   ADSCI_yr          703 non-null    float64
 3   Yield             703 non-null    float64
 4   Acres_Planted     703 non-null    float64
 5   ADSCI_gs          703 non-null    float64
 6   Program           703 non-null    object
 7   Ag District       703 non-null    object
 8   Ag District Code  703 non-null    int64
 9   County ANSI       703 non-null    float64
 10  Commodity         703 non-null    object
 11  Data Item         703 non-null    object
 12  Domain            703 non-null    object
 13  Domain Category   703 non-null    object
 14  Value             703 non-null    float64
 15  CV (%)            0 non-null      float64
 16  avg_precip_count  703 non-null    float64
 17  avg_precip_mean   703 non-null    float64
 18  avg_precip_std    703 non-null    float64
 19  avg_precip_min    703 non-null    float64
 20  avg_precip_25%    703 non-null    float64
 21  avg_precip_50%    703 non-null    float64
 22  avg_precip_75%    703 non-null    float64
 23  avg_precip_max    703 non-null    float64
 24  avg_temp_count    703 non-null    float64
 25  avg_temp_mean     703 non-null    float64
 26  avg_temp_std      703 non-null    float64
 27  avg_temp_min      703 non-null    float64
 28  avg_temp_25%      703 non-null    float64
 29  avg_temp_50%      703 non-null    float64
 30  avg_temp_75%      703 non-null    float64
 31  avg_temp_max      703 non-null    float64
 32  max_temp_count    703 non-null    float64
 33  max_temp_mean     703 non-null    float64
 34  max_temp_std      703 non-null    float64
 35  max_temp_min      703 non-null    float64
 36  max_temp_25%      703 non-null    float64
 37  max_temp_50%      703 non-null    float64
 38  max_temp_75%      703 non-null    float64
 39  max_temp_max      703 non-null    float64
 40  min_temp_count    703 non-null    float64
 41  min_temp_mean     703 non-null    float64
 42  min_temp_std      703 non-null    float64
 43  min_temp_min      703 non-null    float64
 44  min_temp_25%      703 non-null    float64
 45  min_temp_50%      703 non-null    float64
 46  min_temp_75%      703 non-null    float64
 47  min_temp_max      703 non-null    float64
dtypes: float64(39), int64(2), object(7)
memory usage: 269.1+ KB

In [121]:
# Standardize
sc = StandardScaler()
final_ml_num = final_ml.select_dtypes('number')
final_ml_sc = sc.fit_transform(final_ml_num)
final_ml_sc = pd.DataFrame(final_ml_sc, columns=final_ml_num.columns, index=final_ml_num.index)
print(final_ml_sc.shape)
final_ml_sc.head()

(703, 41)

/opt/miniconda3/envs/ba820/lib/python3.8/site-packages/sklearn/utils/extmath.py:847: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/opt/miniconda3/envs/ba820/lib/python3.8/site-packages/sklearn/utils/extmath.py:689: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)

,Year,ADSCI_yr,Yield,Acres_Planted,ADSCI_gs,Ag District Code,County ANSI,Value,CV (%),avg_precip_count,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,-1.45493,1.816667,-1.751462,-1.104774,0.771847,0.162443,-1.635911,-1.104774,NaN,-0.10997,...,0.223901,1.873038,-0.48752,0.604691,-0.161207,1.600031,0.224824,-1.236686,0.223901,1.873038
1,-1.45493,-0.099201,-1.101707,-0.598970,-0.128116,0.672482,-1.581274,-0.598970,NaN,-0.10997,...,0.462595,0.453389,-0.48752,-0.059358,-0.101468,1.087860,-0.509970,-1.417100,0.462595,0.453389
2,-1.45493,0.534223,-0.719498,-0.930151,0.247988,1.182520,-1.472001,-0.930151,NaN,-0.10997,...,0.879973,1.795276,-0.48752,0.695065,-0.213997,1.189038,0.556987,-0.988770,0.879973,1.795276
3,-1.45493,-0.371814,-0.451952,-0.213595,-0.268755,0.672482,-1.417365,-0.213595,NaN,-0.10997,...,0.296107,0.041954,-0.48752,-0.209205,-0.243516,0.986106,-0.328007,-1.431844,0.296107,0.041954
4,-1.45493,-0.216025,-1.331032,2.321447,0.008226,-0.347595,-1.362728,2.321447,NaN,-0.10997,...,0.809412,1.861356,-0.48752,0.716864,-0.278218,1.659146,0.561574,-1.242221,0.809412,1.861356

### Merging USDM-USDA and the Temp and Precip files - Growing Season

In [67]:
gs_temp_precip = gs_acrplanted_pre.merge(gs_acrplanted_temp, how='inner', on=['Year','County'],
                         suffixes=('','_drop')).filter(regex='^(?!.*drop)')
print(gs_temp_precip.shape)
gs_temp_precip.head()

(719, 44)

,Program,Year,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,SURVEY,2019,CENTRAL,50,cayuga,11.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,77.090020,80.920134,5.0,73.465390,6.475191,63.598835,72.181908,73.536051,77.090020,80.920134
1,SURVEY,2019,CENTRAL,50,cortland,23.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,75.424076,79.443288,5.0,71.839454,6.421871,62.222266,70.520350,71.587292,75.424076,79.443288
2,SURVEY,2019,CENTRAL,50,herkimer,43.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,74.668479,78.492434,5.0,70.514132,6.802492,60.629280,67.985406,70.795059,74.668479,78.492434
3,SURVEY,2019,CENTRAL,50,madison,53.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,76.765589,81.324519,5.0,73.232329,6.763674,63.127771,71.532990,73.410773,76.765589,81.324519
4,SURVEY,2019,CENTRAL,50,oneida,65.0,CORN,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,...,77.010881,80.978923,5.0,72.992763,6.971431,62.447200,71.213033,73.313780,77.010881,80.978923

In [68]:
gs_temp_precip.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 719 entries, 0 to 718
Data columns (total 44 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Program           719 non-null    object
 1   Year              719 non-null    int64
 2   Ag District       719 non-null    object
 3   Ag District Code  719 non-null    int64
 4   County            719 non-null    object
 5   County ANSI       719 non-null    float64
 6   Commodity         719 non-null    object
 7   Data Item         719 non-null    object
 8   Domain            719 non-null    object
 9   Domain Category   719 non-null    object
 10  Value             719 non-null    float64
 11  CV (%)            0 non-null      float64
 12  avg_precip_count  719 non-null    float64
 13  avg_precip_mean   719 non-null    float64
 14  avg_precip_std    719 non-null    float64
 15  avg_precip_min    719 non-null    float64
 16  avg_precip_25%    719 non-null    float64
 17  avg_precip_50%    719 non-null    float64
 18  avg_precip_75%    719 non-null    float64
 19  avg_precip_max    719 non-null    float64
 20  avg_temp_count    719 non-null    float64
 21  avg_temp_mean     719 non-null    float64
 22  avg_temp_std      719 non-null    float64
 23  avg_temp_min      719 non-null    float64
 24  avg_temp_25%      719 non-null    float64
 25  avg_temp_50%      719 non-null    float64
 26  avg_temp_75%      719 non-null    float64
 27  avg_temp_max      719 non-null    float64
 28  max_temp_count    719 non-null    float64
 29  max_temp_mean     719 non-null    float64
 30  max_temp_std      719 non-null    float64
 31  max_temp_min      719 non-null    float64
 32  max_temp_25%      719 non-null    float64
 33  max_temp_50%      719 non-null    float64
 34  max_temp_75%      719 non-null    float64
 35  max_temp_max      719 non-null    float64
 36  min_temp_count    719 non-null    float64
 37  min_temp_mean     719 non-null    float64
 38  min_temp_std      719 non-null    float64
 39  min_temp_min      719 non-null    float64
 40  min_temp_25%      719 non-null    float64
 41  min_temp_50%      719 non-null    float64
 42  min_temp_75%      719 non-null    float64
 43  min_temp_max      719 non-null    float64
dtypes: float64(35), int64(2), object(7)
memory usage: 252.8+ KB

In [69]:
gs_final_ml = usdm_usda.merge(gs_temp_precip, how='inner', on=['Year','County'],
                         suffixes=('','_drop')).filter(regex='^(?!.*drop)')
print(gs_final_ml.shape)
gs_final_ml.head()

(703, 48)

,Year,County,ADSCI_yr,Yield,Acres_Planted,ADSCI_gs,Program,Ag District,Ag District Code,County ANSI,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,2002,albany,3918.70,83.0,4300.0,1207.14,SURVEY,EASTERN,60,1.0,...,82.467331,82.692529,5.0,75.710146,7.941833,63.199162,74.548959,75.642751,82.467331,82.692529
1,2002,allegany,898.71,100.0,12700.0,457.29,SURVEY,SOUTHWEST,70,3.0,...,79.883649,80.883084,5.0,74.575059,7.812576,61.353813,75.172073,75.582674,79.883649,80.883084
2,2002,broome,1897.18,110.0,7200.0,770.66,SURVEY,SOUTHERN,80,7.0,...,82.046584,83.193308,5.0,75.788106,8.429460,62.006041,75.483095,76.211505,82.046584,83.193308
3,2002,cattaraugus,468.99,117.0,19100.0,340.11,SURVEY,SOUTHWEST,70,9.0,...,79.259190,80.613192,5.0,74.132932,7.897891,60.735385,74.767399,75.289495,79.259190,80.613192
4,2002,cayuga,714.56,94.0,61200.0,570.89,SURVEY,CENTRAL,50,11.0,...,82.223563,82.838708,5.0,75.794969,8.821819,61.004477,75.850105,77.057992,82.223563,82.838708

In [70]:
gs_final_ml.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 703 entries, 0 to 702
Data columns (total 48 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              703 non-null    int64
 1   County            703 non-null    object
 2   ADSCI_yr          703 non-null    float64
 3   Yield             703 non-null    float64
 4   Acres_Planted     703 non-null    float64
 5   ADSCI_gs          703 non-null    float64
 6   Program           703 non-null    object
 7   Ag District       703 non-null    object
 8   Ag District Code  703 non-null    int64
 9   County ANSI       703 non-null    float64
 10  Commodity         703 non-null    object
 11  Data Item         703 non-null    object
 12  Domain            703 non-null    object
 13  Domain Category   703 non-null    object
 14  Value             703 non-null    float64
 15  CV (%)            0 non-null      float64
 16  avg_precip_count  703 non-null    float64
 17  avg_precip_mean   703 non-null    float64
 18  avg_precip_std    703 non-null    float64
 19  avg_precip_min    703 non-null    float64
 20  avg_precip_25%    703 non-null    float64
 21  avg_precip_50%    703 non-null    float64
 22  avg_precip_75%    703 non-null    float64
 23  avg_precip_max    703 non-null    float64
 24  avg_temp_count    703 non-null    float64
 25  avg_temp_mean     703 non-null    float64
 26  avg_temp_std      703 non-null    float64
 27  avg_temp_min      703 non-null    float64
 28  avg_temp_25%      703 non-null    float64
 29  avg_temp_50%      703 non-null    float64
 30  avg_temp_75%      703 non-null    float64
 31  avg_temp_max      703 non-null    float64
 32  max_temp_count    703 non-null    float64
 33  max_temp_mean     703 non-null    float64
 34  max_temp_std      703 non-null    float64
 35  max_temp_min      703 non-null    float64
 36  max_temp_25%      703 non-null    float64
 37  max_temp_50%      703 non-null    float64
 38  max_temp_75%      703 non-null    float64
 39  max_temp_max      703 non-null    float64
 40  min_temp_count    703 non-null    float64
 41  min_temp_mean     703 non-null    float64
 42  min_temp_std      703 non-null    float64
 43  min_temp_min      703 non-null    float64
 44  min_temp_25%      703 non-null    float64
 45  min_temp_50%      703 non-null    float64
 46  min_temp_75%      703 non-null    float64
 47  min_temp_max      703 non-null    float64
dtypes: float64(39), int64(2), object(7)
memory usage: 269.1+ KB

In [122]:
# Standardize
sc = StandardScaler()
gs_final_ml_num = gs_final_ml.select_dtypes('number')
gs_final_ml_sc = sc.fit_transform(gs_final_ml_num)
gs_final_ml_sc = pd.DataFrame(gs_final_ml_sc, columns=gs_final_ml_num.columns, index=gs_final_ml_num.index)
print(gs_final_ml_sc.shape)
gs_final_ml_sc.head()

(703, 41)

/opt/miniconda3/envs/ba820/lib/python3.8/site-packages/sklearn/utils/extmath.py:847: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/opt/miniconda3/envs/ba820/lib/python3.8/site-packages/sklearn/utils/extmath.py:689: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)

,Year,ADSCI_yr,Yield,Acres_Planted,ADSCI_gs,Ag District Code,County ANSI,Value,CV (%),avg_precip_count,...,max_temp_75%,max_temp_max,min_temp_count,min_temp_mean,min_temp_std,min_temp_min,min_temp_25%,min_temp_50%,min_temp_75%,min_temp_max
0,-1.45493,1.816667,-1.751462,-1.104774,0.771847,0.162443,-1.635911,-1.104774,NaN,0.037743,...,1.689142,0.854181,0.0,0.589097,1.396374,-0.954955,0.930490,0.207458,1.689142,0.854181
1,-1.45493,-0.099201,-1.101707,-0.598970,-0.128116,0.672482,-1.581274,-0.598970,NaN,0.037743,...,0.631002,0.142145,0.0,-0.010525,1.318721,-1.447102,1.177297,0.183126,0.631002,0.142145
2,-1.45493,0.534223,-0.719498,-0.930151,0.247988,1.182520,-1.472001,-0.930151,NaN,0.037743,...,1.516826,1.051242,0.0,0.630280,1.689318,-1.273155,1.300488,0.437816,1.516826,1.051242
3,-1.45493,-0.371814,-0.451952,-0.213595,-0.268755,0.672482,-1.417365,-0.213595,NaN,0.037743,...,0.375256,0.035939,0.0,-0.244083,1.369975,-1.612034,1.017011,0.064381,0.375256,0.035939
4,-1.45493,-0.216025,-1.331032,2.321447,0.008226,-0.347595,-1.362728,2.321447,NaN,0.037743,...,1.589307,0.911703,0.0,0.633906,1.925031,-1.540268,1.445856,0.780662,1.589307,0.911703

## Models for Yield

### Yield as the Y (non-standardized, Complete Year)

In [108]:
# Function for metrics
def regression_results(y_true, y_pred):

    # Regression metrics
    explained_variance=metrics.explained_variance_score(y_true, y_pred)
    mean_absolute_error=metrics.mean_absolute_error(y_true, y_pred) 
    mse=metrics.mean_squared_error(y_true, y_pred)
    median_absolute_error=metrics.median_absolute_error(y_true, y_pred)
    r2=metrics.r2_score(y_true, y_pred)

    print('explained_variance: ', round(explained_variance,4)) 
    print('r2: ', round(r2,4))
    print('MAE: ', round(mean_absolute_error,4))
    print('MSE: ', round(mse,4))
    print('RMSE: ', round(np.sqrt(mse),4))

#### Linear Regression

In [123]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(final_ml[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    final_ml[['Yield']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [110]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [47.29216372]
Coefficient of the predictor is: [[-2.78098031e-03 -3.07767791e+02  6.41982257e+02  3.00532725e+02
  -3.41610112e+02  1.99409844e-01  5.01470207e-01  2.19506459e+00
  -4.82982526e-02]]

In [111]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [114]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.1952
r2:  0.1885
MAE:  15.3707
MSE:  424.597
RMSE:  20.6058

#### Random Forest

In [84]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-84-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [85]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [86]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.3202
r2:  0.3202
MAE:  14.6689
MSE:  355.7067
RMSE:  18.8602

### Yield as the Y (standardized, Complete Year)

#### Linear Regression

In [124]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(final_ml_sc[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    final_ml_sc[['Yield']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [125]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [0.01679836]
Coefficient of the predictor is: [[-0.16754768 -0.23486793  0.34634651  0.24707157 -0.40426709  0.01648855
   0.05635215  0.20233884 -0.00410601]]

In [126]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [127]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.1952
r2:  0.1885
MAE:  0.5875
MSE:  0.6203
RMSE:  0.7876

#### Random Forest

In [128]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-128-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [129]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [130]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.3397
r2:  0.3396
MAE:  0.5489
MSE:  0.5048
RMSE:  0.7105

### Yield as the Y (non-standardized, Growing Season)

#### Linear Regression

In [94]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(gs_final_ml[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    gs_final_ml[['Yield']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [95]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [-1.05233389]
Coefficient of the predictor is: [[-2.27702920e-03 -4.48203470e+02  1.56641576e+02  6.34464407e+01
   4.20222670e+01  1.28299715e+01  2.72540696e-01 -2.77768634e+00
  -7.30664428e+00]]

In [96]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [97]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.2365
r2:  0.2357
MAE:  15.3439
MSE:  399.9093
RMSE:  19.9977

#### Random Forest

In [98]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-98-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [99]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [100]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.2653
r2:  0.2645
MAE:  15.3055
MSE:  384.8231
RMSE:  19.6169

### Yield as the Y (standardized, Growing Season)

#### Linear Regression

In [131]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(gs_final_ml_sc[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    gs_final_ml_sc[['Yield']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [132]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [0.01934118]
Coefficient of the predictor is: [[-0.13718579 -0.52619906  0.16913915  0.0789556   0.06538235  0.90197049
   0.02395968 -0.23768274 -0.64660908]]

In [133]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [134]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.2365
r2:  0.2357
MAE:  0.5865
MSE:  0.5842
RMSE:  0.7643

#### Random Forest

In [135]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-135-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [136]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [137]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.2742
r2:  0.274
MAE:  0.5776
MSE:  0.555
RMSE:  0.745

## Models for Acres Planted

### Acres Planted as the Y (non-standardized, Complete Year)

#### Linear Regression

In [142]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(final_ml[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    final_ml[['Acres_Planted']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [143]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [-17129.13089955]
Coefficient of the predictor is: [[-1.62489569e+00 -6.46701307e+05  3.72785417e+05  2.43462669e+05
  -1.56240257e+04  4.86355218e+02  3.99544927e+02  1.14280153e+02
   6.83143637e+02]]

In [144]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [145]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.0839
r2:  0.0829
MAE:  12698.262
MSE:  236813626.3501
RMSE:  15388.75

#### Random Forest

In [146]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-146-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [147]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [148]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.0117
r2:  0.0117
MAE:  12686.219
MSE:  255185605.1905
RMSE:  15974.5299

### Acres Planted as the Y (standardized, Complete Year)

#### Linear Regression

In [149]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(final_ml_sc[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    final_ml_sc[['Acres_Planted']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [150]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [-0.00849557]
Coefficient of the predictor is: [[-0.1542299  -0.77751158  0.31684677  0.3153305  -0.02912951  0.06335662
   0.07073487  0.01659607  0.09149622]]

In [151]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [152]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  0.0839
r2:  0.0829
MAE:  0.7646
MSE:  0.8586
RMSE:  0.9266

#### Random Forest

In [153]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-153-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [154]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [155]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  -0.0136
r2:  -0.0136
MAE:  0.7799
MSE:  0.949
RMSE:  0.9742

### Acres Planted as the Y (non-standardized, Growing Season)

#### Linear Regression

In [156]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(gs_final_ml[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    gs_final_ml[['Acres_Planted']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [157]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [-61517.82990381]
Coefficient of the predictor is: [[-1.27792192e+00 -1.95198998e+05  4.63493594e+04  6.72275124e+03
  -6.79422647e+03  4.12121894e+03  3.28680894e+02 -1.55707076e+03
  -1.11870852e+03]]

In [158]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [159]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  -0.0138
r2:  -0.014
MAE:  12996.5677
MSE:  261828402.1843
RMSE:  16181.1125

#### Random Forest

In [160]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-160-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [161]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [162]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  -0.0119
r2:  -0.0119
MAE:  12778.6571
MSE:  261292441.019
RMSE:  16164.5427

### Acres Planted as the Y (standardized, Growing Season)

#### Linear Regression

In [163]:
# Split the data frame
train_ratio = 0.75
validation_ratio = 0.15
test_ratio = 0.10

# train is now 75% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(gs_final_ml_sc[['ADSCI_yr', 
                                                                'avg_precip_mean', 'avg_precip_25%',
                                                               'avg_precip_50%', 'avg_precip_75%',
                                                               'avg_temp_mean', 'avg_temp_25%',
                                                               'avg_temp_50%', 'avg_temp_75%']],
                                                    gs_final_ml_sc[['Acres_Planted']], 
                                                    test_size=1 - train_ratio, 
                                                    random_state = 0)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, 
                                                test_size=test_ratio/(test_ratio + validation_ratio), 
                                                random_state = 0)

In [164]:
# Fit the model
lr = LinearRegression()
lr.fit(x_train, y_train)
print(f'Intercept is: {lr.intercept_}')
print(f'Coefficient of the predictor is: {lr.coef_}')

Intercept is: [-0.00840526]
Coefficient of the predictor is: [[-0.12129626 -0.36103975  0.07884668  0.0131803  -0.01665419  0.45645178
   0.04552256 -0.20990625 -0.15597082]]

In [165]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [166]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  -0.0138
r2:  -0.014
MAE:  0.7826
MSE:  0.9493
RMSE:  0.9743

#### Random Forest

In [167]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

<ipython-input-167-58dbcc52fb98>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [168]:
# Predict on Validation set
y_val_pred = lr.predict(x_val)

In [169]:
# Metrics obtained on the validation set
regression_results(y_val, y_val_pred)

explained_variance:  -0.0014
r2:  -0.0014
MAE:  0.7674
MSE:  0.9375
RMSE:  0.9683